package com.example.tembeakenyasafaris.navigation

const val ROUT_HOME="home"
const val ROUT_ABOUT="about"
const val ROUT_DETAIL="detail"
const val ROUT_SPLASH="splash"
const val ROUT_PROPERTY="property"
const val ROUT_LOGIN="login"
const val ROUT_SIGNUP="signup"
const val ROUT_NAIROBIPARK="nairobipark"
const val ROUT_AMBOSELI="amboseli"
const val ROUT_MAPNAIROBI="mapnairobi"
const val ROUT_NAIROBIMUSEUM="nairobimuseum"
const val ROUT_MAASAIMARA="maasaimara"
const val ROUT_US="us"
const val ROUT_MAPAMBOSELI="mapamboseli"
const val ROUT_MAPMAASAI="mapmaasai"
const val ROUT_LAKENAIVASHA="lakenaivasha"
const val ROUT_BOMAS="bomas"
const val ROUT_MAPBOMAS="mapbomas"
const val ROUT_MAPLAKE="maplake"
const val ROUT_ELEMENTAITA="elementaita"
const val ROUT_MOUNTKENYA="mountkenya"
const val ROUT_TSAVO="tsavo"
const val ADD_PRODUCTS_URL = "add_products"
const val VIEW_PRODUCTS_URL = "view_products"